Add: mrb_search
pylover/mrb pull request #1
Opened 2023-09-02 19:29 UTC by hosseinsokhandan

- Add mrb_serach to mrb.c
- Write tests form mrb_serach to mrb_test.c
- Lint some suggestions with prettyc linter

2023-09-04 13:10 UTC, pylover requested changes

2023-09-04 13:10 UTC, pylover commented on mrb.c
> +mrb_search(struct mrb *b, char *key, int *start_index) {
```C
/*
if index == -1, search from the first available index.
if limit == -1, search till end.
*/
int
mrb_search(struct mrb *b, const char *needle, size_t len, int index, int limit);
```

2023-09-04 13:10 UTC, pylover commented on mrb_test.c
> +test_mrb_search() {
Do more tests.

2024-01-20 11:38 UTC, pycub commented
Already done!

2024-01-20 11:38 UTC, closed without merging